name: Build & Test
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release type"
        required: true
        default: "Debug"
  pull_request:
    branches:
      - main

env:
  DEFAULT_BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libzip-dev ccache
      - name: Fetch repository
        uses: actions/checkout@v7
      - name: Cache
        uses: actions/cache@v6
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-
      - name: Cache FetchContent
        uses: actions/cache@v6
        with:
          path: ${{github.workspace}}/build/_deps
          key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-
      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.1
        with:
          version: '6.11.1'
          cache: true
      - name: Configure
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE="${{ inputs.releaseType || env.DEFAULT_BUILD_TYPE }}" -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build